(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var L0=function(a){a.V("cardstatechange",a.Kh()&&a.wk()?1:0)},M0=function(a,b){var c=g.Na(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},PFa=function(a){var b=g.qg(a);
a=g.wg(a);return new g.Xf(b.x,b.y,a.width,a.height)},QFa=function(a){return Math.pow(a,3)},RFa=function(a){return 3*a*a-2*a*a*a},P0=function(a){a=g.Qa(a);
delete N0[a];g.Rb(N0)&&O0&&O0.stop()},TFa=function(){O0||(O0=new g.J(function(){SFa()},20));
var a=O0;a.isActive()||a.start()},SFa=function(){var a=g.Ta();
g.Db(N0,function(b){UFa(b,a)});
g.Rb(N0)||TFa()},Q0=function(a,b,c,d){g.pn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.I=0;this.B=null},UFa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.B);a.B=b;VFa(a,a.progress);1==a.progress?(a.bb=0,P0(a),a.onFinish(),a.yu()):a.pc()&&a.xz()},VFa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},WFa=function(a,b){g.Bl.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.bb},R0=function(a,b,c,d,e){Q0.call(this,b,c,d,e);
this.element=a},S0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
R0.call(this,a,b,c,d,e)},T0=function(a){g.F.call(this);
this.l=a||window;this.i=[]},U0=function(a){return a.baseUrl||null},V0=function(a,b){return g.Ke(g.Pc(a,b,void 0),function(c){return!!c})},XFa=function(a,b,c){function d(oa){var sb,Cc,te,Ua=oa.hovercardButton;
if(!Ua)return null;Ua=Ua.subscribeButtonRenderer;if(!Ua)return null;var Pb=f(Ua.unsubscribedButtonText),th=f(Ua.subscribedButtonText);if(Ua.subscribed){var tl=f(Ua.subscriberCountWithUnsubscribeText);var Dj=f(Ua.subscriberCountText)}else tl=f(Ua.subscriberCountText),Dj=f(Ua.subscriberCountWithSubscribeText);var Qf=null;return oa.signinEndpoint&&(Qf=M0(oa,"signinEndpoint","webNavigationEndpointData","url"),Qf||(Qf=null===(te=null===(Cc=null===(sb=Ua.signInEndpoint)||void 0===sb?void 0:sb.commandMetadata)||
void 0===Cc?void 0:Cc.webCommandMetadata)||void 0===te?void 0:te.url),!Qf)?null:Pb&&(th||Qf)?{subscribed:Ua.subscribed,subscribeText:Pb,subscribeCount:tl,unsubscribeText:th,unsubscribeCount:Dj,enabled:Ua.enabled,signinUrl:Qf,classic:oa.useClassicSubscribeButton}:null}
function e(oa){if(oa){var sb=[],Cc=oa.videoId;Cc&&sb.push("v="+Cc);(Cc=oa.playlistId)&&sb.push("list="+Cc);(oa=oa.startTimeSeconds)&&sb.push("t="+oa);return"/watch?"+sb.join("&")}}
function f(oa){if(!oa)return null;var sb=oa.simpleText;return sb?sb:oa.runs?g.Pc(oa.runs,function(Cc){return Cc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,x=!1,y=null,E=null,B=null,G=null,I=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=M0(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):E=f(b.subscribersText)}else"WEBSITE"===
h?((B=M0(l,"urlEndpoint","url"))&&(m=B),n=!0,p="new",B=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=M0(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=M0(b,"title","accessibility","accessibilityData","label");var O=b.endpoint?b.endpoint.clickTrackingParams:null,fa="";if(b.metadata){var ra=f(b.metadata);ra&&(fa=ra)}return{id:"element-"+c,type:h,title:f(b.title),metadata:fa,callToAction:f(b.callToAction),
iG:b.image,iconUrl:B,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:E,isSubscribe:x,targetUrl:m||null,XO:n,le:O?{itct:O}:null,wT:p,Ks:a?a:null,aP:b.isPlaceholder,impressionUrls:V0(b.impressionUrls||[],U0),QO:V0(b.hovercardShowUrls||[],U0),clickUrls:V0(l.loggingUrls||[],U0),visualElement:g.ru(b.trackingParams),
productPrice:G,additionalFeesText:I}},W0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:V0(a.impressionUrls||[],U0),elements:V0(a.elements||[],function(d,e){return XFa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.ru(a.trackingParams));return c},X0=function(a){g.SL.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.W=!0;this.I=0;a=a.T();this.L=g.ID(a)||g.LD(a);this.events=new g.KL(this);g.H(this,this.events);this.events.N(this.player,g.yw("creatorendscreen"),this.je);this.events.N(this.player,g.zw("creatorendscreen"),this.ag);this.events.N(this.player,"resize",this.kb);this.events.N(window,"focus",this.BS);this.load();var b=g.Fe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.xi(this,function(){g.Je(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},YFa=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},Y0=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},ZFa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=W0(f,YFa(a))));Z0(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.ao;d&&(c.postParams={ad_tracking:d});if(b=g.sia(b))if(b=g.Jc(b),b=g.Fc(b))a.u=g.Zp(b,c)},Z0=function(a,b,c){c=void 0===c?!0:c;
a.player.Cf("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&$Fa(a);c=[];d=new g.vw(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.W({D:"div",K:"ytp-ce-shadow"}),g.IL(a.player,a.l.element,4),a.B=new g.xK(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=aGa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.IL(a.player,f.element,4);var h=new g.vw(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);bGa(a,f,e)}else g.vt(new g.cs("buildEndscreenElement null",
e))}a.player.Ud(c);a.kb()}},$Fa=function(a){var b=g.wu(),c=g.yu();
c&&b&&a.endscreen.visualElement&&g.Lu(c,b,a.endscreen.visualElement)},aGa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ba:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.Ks||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:$0(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:a1(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",Ba:["ytp-ce-video-title"].concat(g.ma(c)),U:{dir:g.vn(b.title||
"")},ma:b.title},{D:"div",K:"ytp-ce-video-duration",ma:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ba:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.Ks||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:$0(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:a1(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",Ba:["ytp-ce-playlist-title"].concat(g.ma(c)),U:{dir:g.vn(b.title||"")},ma:b.title},{D:"div",K:"ytp-ce-playlist-count",S:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",ma:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={D:"div",Ba:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.Ks||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",Ba:["ytp-ce-channel-title","ytp-ce-link"],U:{href:a1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.vn(b.title||"")},ma:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",S:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",ma:b.subscribersText}:"",b.metadata?{D:"div",Ba:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ma:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:$0(b)}]};c=new g.W(c);var d=g.pe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.le.itct}else e="endscreen",f=null;e=new g.UM(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ba:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.Ks||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-website-title",U:{dir:g.vn(b.title||"")},ma:b.title},{D:"div",K:"ytp-ce-website-metadata",ma:b.metadata},{D:"a",Ba:["ytp-ce-website-goto","ytp-ce-link"],U:{href:a1(a,b.targetUrl),target:"_blank",tabindex:"-1"},ma:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:$0(b)},{D:"div",
K:"ytp-ce-expanding-icon",U:cGa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",S:[{D:"div",K:"ytp-ce-merchandise-price",ma:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",K:"ytp-ce-merchandise-additional-fees",ma:b.additionalFeesText})),a={D:"div",Ba:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.Ks||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-merchandise-title",U:{dir:g.vn(b.title||"")},ma:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",ma:b.metadata},{D:"a",Ba:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:a1(a,b.targetUrl),target:"_blank",tabindex:"-1"},ma:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",U:$0(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",ma:b.callToAction||void 0}]}]},c=new g.W(a)}b.aP&&g.K(c.element,"ytp-ce-placeholder");return c},$0=function(a){if(a.iG)var b=a.iG.thumbnails;
return cGa(b?b[b.length-1].url:null)},cGa=function(a){return a?{style:"background-image: url("+a+")"}:{}},bGa=function(a,b,c){function d(m){m&&(b.Na("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.K(b.element,"ytp-ce-force-expand"),b1(a,c.id,!0)):(g.mn(b.element,"ytp-ce-force-expand"),g.mn(b.element,"ytp-ce-element-hover"),b1(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Na("mouseenter",function(){c1(a,b,c)});
b.Na("mouseleave",function(){d1(a,b,c)});
a.player.T().i||b.Na("click",function(){g.K(b.element,"ytp-ce-element-hover")});
b.Na("click",function(m){dGa(a,c,m)});
b.Na("keypress",function(m){dGa(a,c,m)});
b.Na("focus",function(){c1(a,b,c)});
b.Na("blur",function(){d1(a,b,c)});
b.Na("touchstart",function(){c1(a,b,c)});
var l=g.re("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.mn(b.element,"ytp-ce-element-hover");g.mn(b.element,"ytp-ce-force-expand")});
b.Na("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.re("ytp-sb-subscribe",b.element));d(g.re("ytp-sb-unsubscribe",b.element));b.Na("focus",f);b.Na("blur",h)},dGa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.kn(d,"ytp-ce-element");){g.kn(d,"subscribe-label")&&e1(a,b);
if(g.kn(d,"ytp-ce-channel-subscribe"))return;d=g.Le(d)}if(!d||g.kn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])d1(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.wT)e1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Jc(a1(a,b.targetUrl)),c=g.Fc(c),g.uI(c,void 0,b.le);else{var e=a.player.getVideoData().C,f=function(){var h=a1(a,b.targetUrl),l=b.le,m=g.Ip(h);e&&m&&(m.v||m.list)?a.player.Rj(m.v,l,m.list,!1):g.tI(h,l)};
e1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},a1=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.pE(a)+b}else return"";return b},c1=function(a,b,c){g.kn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.K(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.J(function(){g.K(b.element,"ytp-ce-element-hover")},200)).start():g.K(b.element,"ytp-ce-element-hover"),f1(a,c.QO),b1(a,c.id,!0))},d1=function(a,b,c){g.mn(b.element,"ytp-ce-element-hover");
g.mn(b.element,"ytp-ce-force-expand");b1(a,c.id,!1)},b1=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.L(a.i[e].element,"ytp-ce-element-shadow-show",c)},f1=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||Y0(a))c&&c();else{b=eGa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.uq(b[a],d)}},e1=function(a,b,c){f1(a,b.clickUrls,c);
(a=g.yu())&&b.XO&&g.Ou(a,b.visualElement)},eGa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(fGa(b[d],c));return a},fGa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},gGa=function(a){return Array.isArray(a)&&a.length?a[0]:a},g1=function(a){return"string"===typeof a?a:""},h1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},hGa=function(a){this.externalId=a},iGa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},i1=function(a){return a.value?a.value:null},j1=function(a){if(!a)return null;
var b=g.Jc(g1(a.value));b=g.Fc(b);if(!b)return null;var c=h1(a.target,jGa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new iGa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},kGa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},nGa=function(a){if(!a)return null;
var b=h1(a.type,lGa),c=h1(a.trigger,mGa),d=gGa(a.url);d=j1(d?d:null);a=gGa(a.subscribeData);var e=a?a:null;e?(a=g1(e.external_user_id),e=g1(e.subscription_token),a=a&&e?new hGa(a):null):a=null;return b?new kGa(b,c,d,a):null},oGa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},qGa=function(a){return(a=pGa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},pGa=function(a,b){return g.db(a.action,b,void 0)},rGa=function(a,b){this.context=a;
this.i=b},l1=function(a){return a.customMessage?k1("div","iv-card-message",a.customMessage):""},m1=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",U:{style:a},S:c}},n1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(k1("li","",c.value));return{D:"ul",K:"iv-card-meta-info",S:b}},k1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.vn(c);return{D:a,U:b,ma:c}},sGa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Tv&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Tv+");");c.dir=g.vn(a.customMessage);var d=[{D:"span",ma:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ba:b,U:c,S:d}},o1=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.le,c.tracking.click,5)}},tGa=function(a,b){this.merchant=a;
this.price=b},uGa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},vGa=function(a,b){return b?b:uGa(a)?"current":"new"},p1=function(a,b){g.F.call(this);
var c=this;this.element=a;this.context=b;this.Xa=!1;this.Ma=new Map;this.Ra=new Map;this.context.G.addEventListener(g.yw("annotations_module"),function(d){(d=c.Ma.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.zw("annotations_module"),function(d){(d=c.Ra.get(d))&&d.apply(c)})},q1=function(a,b,c,d,e,f,h){a.context.i.Na(b,"click",function(l){a.yz(c,d,e,f||[],h||0,l)});
a.context.i.Na(b,"touchstart",function(){a.Xa=!1});
a.context.i.Na(b,"touchmove",function(){a.Xa=!0})},wGa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},r1=function(a,b,c){return{cH:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
eK:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
sy:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},u1=function(a,b,c){p1.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Da=this.ub=this.u=this.Me=!1;this.ra=null;this.cards=[];this.ib=this.L=this.Aa=this.C=this.Ga=this.i=null;this.X=[];this.J=this.Ge=this.Ca=null;this.I=0;this.va=new g.J(g.Ka,c.B.ld?4E3:3E3);g.H(this,this.va);this.Ya=new g.J(g.Ka);g.H(this,this.Ya);this.Y=new rGa(c,function(e,f,h,l,m,n){q1(d,e,f,h,l,m,n)});
this.W=new g.W({D:"div",K:"iv-drawer",U:{id:"iv-drawer"},S:[{D:"div",K:"iv-drawer-header",U:{"aria-role":"heading"},S:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ba:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.H(this,this.W);this.B=this.W.element;this.Ta=new g.xK(this.W,330);g.H(this,this.Ta);this.tb=g.re("iv-drawer-header-text",this.B);this.l=g.re("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.ub&&s1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.ub=d.u)&&t1(d)})},xGa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){s1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){t1(a)});
var c=b.headerText;g.Ne(a.tb,c);a.L&&a.L.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ca=g.ru(b.trackingParams);a.J=g.ru(b.closeTrackingParams);a.Ge=g.ru(b.iconTrackingParams)},yGa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Fw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,le:v1(a,c,b,d),sponsored:!1,tracking:r1(d,e,d.command),Al:d.trackingParams?g.ru(d.trackingParams):null,Wi:e.trackingParams?
g.ru(e.trackingParams):null,Ge:f&&f.trackingParams?g.ru(f.trackingParams):null,imageUrl:w1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Fw(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Tv:null,title:d.title?g.Fw(d.title):"",customMessage:d.callToAction?g.Fw(d.callToAction):"",url:d.command.urlEndpoint.url?j1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};x1(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.Fw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,le:v1(a,c,b,d),sponsored:!1,tracking:r1(d,e,d.endpoint),Al:d.trackingParams?g.ru(d.trackingParams):null,Wi:e.trackingParams?g.ru(e.trackingParams):null,Ge:f&&f.trackingParams?g.ru(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Fw(d.customText):null,pJ:w1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Fw(d.channelName):"",metaInfo:[d.subscriberCountText?g.Fw(d.subscriberCountText):""],url:j1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};x1(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.Fw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,le:v1(a,c,b,d),sponsored:!1,tracking:r1(d,e,d.action),Al:d.trackingParams?g.ru(d.trackingParams):null,Wi:e.trackingParams?g.ru(e.trackingParams):null,Ge:f&&f.trackingParams?g.ru(f.trackingParams):
null,hv:w1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Fw(d.customMessage):null,playlistVideoCount:g.Fw(d.playlistVideoCount),title:d.playlistTitle?g.Fw(d.playlistTitle):"",metaInfo:[d.channelName?g.Fw(d.channelName):"",d.videoCountText?g.Fw(d.videoCountText):""],url:j1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:wGa(d.action)})};x1(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.Fw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,le:v1(a,c,b,d),sponsored:!1,tracking:r1(d,e,d.action),Al:d.trackingParams?g.ru(d.trackingParams):null,Wi:e.trackingParams?g.ru(e.trackingParams):null,Ge:f&&f.trackingParams?g.ru(f.trackingParams):null,hv:w1(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.Fw(d.lengthString):null,customMessage:d.customMessage?g.Fw(d.customMessage):null,title:d.videoTitle?g.Fw(d.videoTitle):"",metaInfo:[d.channelName?g.Fw(d.channelName):"",d.viewCountText?g.Fw(d.viewCountText):""],isLiveNow:!!d.badge,url:j1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:wGa(d.action)})};x1(a,b)}a.I++},w1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},v1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},AGa=function(a,b){if(b=zGa(a,b))b===a.i&&(a.i=null),a.G.removeCueRange(b.card.id),g.Je(b.bA),g.lb(a.cards,b),a.Vv(),y1(a)},s1=function(a,b,c){if(!a.u){a.Ta.show();
a.Ga=new g.J(function(){g.K(a.context.G.getRootNode(),g.TR.IV_DRAWER_OPEN)},0);
a.Ga.start();a.ra=g.cp(a.l,"mousewheel",function(h){a.va.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.yu();d&&a.Ca&&a.J&&g.Mu(d,[a.Ca,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.HH||(f.HH=!0,BGa(a.context.logger,f.card.tracking.cH,b)),d&&g.Mu(d,[f.card.Al]);L0(a.G);c&&(a.C=new g.J(function(){a.Aa=a.L;a.ib.focus()},330),a.C.start())}},t1=function(a){a.u&&(a.Ta.hide(),g.dp(a.ra),a.ra=null,g.mn(a.context.G.getRootNode(),g.TR.IV_DRAWER_OPEN),a.u=!1,L0(a.G),a.C&&a.C.stop(),a.C=new g.J(function(){a.Aa&&(a.Aa.focus(),a.Aa=null)},330),a.C.start())},
DGa=function(a){g.ln(a.element,[g.TR.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.IL(a.G,a.B,5);CGa(a);a.L=g.re("ytp-cards-button",a.G.getRootNode());a.ib=g.re("iv-drawer-close-button",a.B);a.Me=!0},CGa=function(a){var b=g.re("iv-drawer-close-button",a.B);
a.context.i.Na(b,"click",a.IN,a);a.context.i.Na(a.l,"touchend",function(){a.va.start()});
a.context.i.Na(a.l,"scroll",a.UN,a);a.context.l.subscribe("onHideControls",function(){a.Da=!0});
a.context.l.subscribe("onShowControls",function(){a.Da=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Da=g.kn(a.G.getRootNode(),"ytp-autohide")});
a.X.push(g.Io("iv-button-shown",a.eP,a));a.X.push(g.Io("iv-button-hidden",a.dP,a));a.X.push(g.Io("iv-teaser-shown",a.hM,a));a.X.push(g.Io("iv-teaser-hidden",a.gP,a));a.X.push(g.Io("iv-teaser-clicked",a.gM,a))},x1=function(a,b){a.Me||DGa(a);
AGa(a,b.id);var c=EGa(a,b);if(c){var d={card:b,bA:c.element,HH:!1},e=FGa(a,d);g.tb(a.cards,e,0,d);c.xa(a.l,e);a.Vv();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,y1(a),GGa(a,d),s1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&HGa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){HGa(a,d)}),y1(a))}},EGa=function(a,b){switch(b.type){case "simple":a=a.Y;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",ma:b.displayDomain}:void 0;var d=sGa(b);c={D:"div",Ba:["iv-card"],S:[{D:"a",K:"iv-click-target",U:{href:b.url?i1(b.url)||"":""},S:[m1(b.imageUrl,c),{D:"div",K:"iv-card-content",S:[k1("h2",void 0,b.title),d]}]}]};c=new g.W(c);o1(a,g.qe("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.Y,c={D:"div",Ba:["iv-card","iv-card-channel"],S:[{D:"a",Ba:["iv-click-target"],U:{href:i1(b.url)||"","data-ytid":b.channelId},S:[m1(b.pJ),
{D:"div",K:"iv-card-content",S:[l1(b),{D:"h2",K:"iv-card-primary-link",ma:b.title},n1(b)]}]}]},c=new g.W(c),o1(a,g.qe("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.Y,c={D:"div",Ba:["iv-card","iv-card-playlist"],S:[{D:"a",K:"iv-click-target",U:{href:i1(b.url)||""},S:[m1(b.hv,{D:"div",K:"iv-card-image-overlay",S:[{D:"span",K:"iv-card-playlist-video-count",ma:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",S:[l1(b),k1("h2","iv-card-primary-link",b.title),n1(b)]}]}]},c=new g.W(c),
o1(a,g.qe("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.Y;var e=!g.ib(b.offers);c=["iv-card"];d="";var f=sGa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",ma:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",ma:f.merchant}),f={D:"div",S:e});e=b.url?i1(b.url)||"":"";c={D:"div",Ba:c,U:{tabindex:"0"},S:[{D:"a",Ba:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",S:[b.sponsored?{D:"div",K:"iv-card-sponsored",S:["Sponsored",{D:"div",K:"iv-ad-info-container",S:[{D:"div",K:"iv-ad-info",ma:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",S:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",U:{href:e},S:[k1("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.Fe("span");g.Ne(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.bd(d,"adInfo");o1(a,g.qe("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.Y,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",ma:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ba:["yt-badge","yt-badge-live"],ma:"LIVE NOW"}:null,d={D:"div",Ba:["iv-card","iv-card-video"],S:[{D:"a",K:"iv-click-target",U:{href:(null===(c=b.url)||void 0===c?void 0:i1(c))||""},S:[m1(b.hv,d),{D:"div",K:"iv-card-content",S:[l1(b),k1("h2","iv-card-primary-link",b.title),n1(b),f]}]}]},c=new g.W(d),
o1(a,g.qe("iv-click-target",c.element),b,b.url),c;default:return null}},FGa=function(a,b){if(0===a.cards.length)return 0;
a=g.eb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},IGa=function(a){return a.i?"productListing"===a.i.card.type:g.Zg(a.cards,function(b){return"productListing"===b.card.type})},y1=function(a){g.L(a.G.getRootNode(),"ytp-cards-shopping-active",IGa(a))},HGa=function(a,b){if(!g.kn(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.yu(),d=a.i?a.i.card.Ge:a.Ge;
c&&d&&g.Nu(c,[d]);a.i=b;y1(a)}if(c="none"!=a.element.style.display)g.S(a.context.G.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.G.getPresentingPlayerType()?(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.G.getAdState();c&&b.card.teaserDurationMs&&a.G.Pr(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ya.isActive()||((!a.u||!a.va.isActive()&&a.Da)&&GGa(a,b),a.Ya.start(910+b.card.teaserDurationMs))}},
GGa=function(a,b){a.W.vb?(b=new Q0([0,
a.l.scrollTop],[0,b.bA.offsetTop],600,RFa),a.context.u.Na(b,"animate",function(c){a.l.scrollTop=c.y}),a.context.u.Na(b,"finish",function(c){a.l.scrollTop=c.y}),b.play()):(g.KJ(a.W,!0),a.l.scrollTop=b.bA.offsetTop,g.KJ(a.W,!1))},z1=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},zGa=function(a,b){return g.db(a.cards,function(c){return c.card.id===b})},A1=function(a,b,c){p1.call(this,a,b);
this.annotation=c;this.isActive=!1},JGa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},B1=function(a,b,c){A1.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.I=this.C=null},KGa=function(a,b){var c=void 0===c?0:c;
var d=PFa(b).width;g.og(b,d);c=new S0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,QFa);g.H(a,c);a.context.u.Na(c,"begin",function(){g.xg(b,!0)});
c.play()},NGa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ba:["iv-branding-context-name"],ma:b.channel_name}),d=a.createElement({D:"div",Ba:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.UM(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.G),a.i.xa(d));var f=a.createElement({D:"div",Ba:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ba:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.xg(h,!1);var l=a.createElement({D:"div",Ba:["branding-context-container-outer"]});l.appendChild(h);g.gg(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.J(function(){LGa(a,h,l)},500);
g.H(a,a.u);a.context.i.Na(a.element,"mouseover",function(){MGa(a,h,l,f,b.image_height)});
a.context.i.Na(a.element,"mouseout",function(){a.u.start()})}},MGa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.wg(b);a.i||(b.style.width=g.ng(f.width,!0),c.style.width=g.ng(f.width,!0));g.gg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.gg(d,"right","1px");a.B=!0;g.xg(b,!0);a.C=new g.J(function(){g.K(this.element,"iv-branding-active")},0,a);
a.C.start()}},LGa=function(a,b,c){g.mn(a.element,"iv-branding-active");
a.I=new g.J(function(){g.xg(b,!1);a.i||(c.style.width=g.ng(0,!0))},250);
a.I.start();a.B=!1},OGa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.G=f;this.l=h},C1=function(a,b,c){A1.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.W=!1;this.I=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ba:["iv-promo-contents"]});this.C=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.xg(d.u,!1);g.xg(d.l,!0)},700,this);
g.H(this,this.C)},PGa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=qGa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ba:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",ma:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",ma:b.playlist_length.toString()}),h.appendChild(f));e&&q1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.id(f,i1(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
ma:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",K:"iv-promo-link",ma:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ba:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ba:["iv-button","iv-promo-button"],S:[{D:"span",K:"iv-button-content",ma:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&q1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.i,
"iv-click-target");e&&q1(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",ma:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",ma:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ba:["yt-badge","iv-promo-badge-live"],ma:"LIVE NOW"})),g.K(a.i,"iv-click-target"),e&&q1(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);p&&
a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",Ba:["iv-promo-expand","ytp-button"]});a.l.title="Expand";a.context.i.Na(a.l,"click",function(r){D1(a,5E3,r)});
c.appendChild(a.l);g.xg(a.l,!1);a.context.i.Na(a.element,"mouseover",a.yO,a);a.context.i.Na(a.element,"mouseout",a.xO,a);a.context.i.Na(a.element,"touchend",function(r){D1(a,5E3,r)});
a.u=a.createElement({D:"button",Ba:["iv-promo-close","ytp-button"]});a.u.title="Close";a.context.i.Na(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.uO:a.tO,a);c.appendChild(a.u);g.ln(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},D1=function(a,b,c){c.stopPropagation();
QGa(a);RGa(a,b);a.i.focus()},SGa=function(a){a.isCollapsed||a.L||a.B||(g.K(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},QGa=function(a){a.C.stop();
a.isCollapsed&&(g.nn(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.xg(a.l,!1),g.xg(a.u,!0))},RGa=function(a,b){a.B||(a.B=g.Fm(function(){E1(this);
SGa(this)},b,a))},E1=function(a){a.B&&(g.A.clearTimeout(a.B),a.B=null)},TGa=function(a){this.G=a},BGa=function(a,b,c){b&&(c?F1(a,b.map(function(d){return g.Zm(d,c)})):F1(a,b))},F1=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.uq(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},G1=function(a){g.SL.call(this,a);
var b=this;this.W=!1;this.loadNumber=0;this.J={};this.logger=new TGa(this.player);this.C=new g.KL(this);this.I=this.u=null;this.events=new g.KL(this);this.L=this.i=null;this.X=[];g.H(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.V("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.V("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.V("onShowControls")});
this.C.N(this.player,"resize",function(d){b.V("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.V("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.iM,this);this.subscribe("resize",this.Dx,this);this.player.T().L.subscribe("vast_info_card_add",this.dJ,this);g.H(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.W({D:"div",Ba:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.l);g.IL(this.player,this.l.element,4);this.l.hide();this.B=new g.W({D:"div",Ba:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Mp()&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.xi(this,function(){g.Je(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},UGa=function(a){a=a.createElement({D:"div",
Ba:["annotation","annotation-type-custom"]});g.xg(a,!1);return a},VGa=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.KJ(a.l,b);g.KJ(a.B,b)},WGa=function(a,b,c){a.W=!0;
a.I=g.Zp(b,c)},XGa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(XGa(a,e))}return c},$Ga=function(a){var b=a.player.getVideoData();
if(b.ra){var c=a.player.T().L.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Up(h)&&h.responseXML?h.responseXML:null)&&H1(a,h)}};
g.tp()&&(d.onFinish=YGa(a,d.onFinish));d.postParams={ic_only:"1"};ZGa(d,c);a.W=!0;g.Zp(b.ra,d)}}},ZGa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Us&&(a.postParams.ic_coll=b.Us);b.Zv&&(a.postParams.ic_xml=b.Zv);b.tv&&(a.postParams.ic_track=b.tv)},aHa=function(a){var b=new g.W({D:"div"});
g.xg(b.element,!1);var c=new u1(a.player,b.element,I1(a));g.H(c,b);b.xa(a.l.element);c.Ru();return c},I1=function(a){if(!a.L){var b=new T0(a);
g.H(a,b);var c=new g.x_(a);g.H(a,c);a.L=new OGa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.qe)}return a.L},H1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.yu();if(e){var f=g.wu();f&&g.Eu(g.Ro("use_default_events_client")?void 0:g.mt,e,f,[g.ru(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=XGa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=h1(f.type,bHa),p=h1(f.style,cHa),r=g1(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=nGa;if(null==u)var x=null;else if(g.Na(u)){l=[];for(var y=g.q(u),E=y.next();!E.done;E=
y.next()){var B=f(E.value);B&&l.push(B)}x=l}else{var G=f(u);x=G?[G]:[]}e=m&&n?new oGa(m,n,p,x,t):null}else e=null}catch(sb){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=UGa(f),O=null;switch(l.type){case "branding":if(f.player.T().Ub)break;f.l.element.appendChild(I);O=new B1(I,I1(f),l);break;case "promotion":g.IL(f.player,I,4),O=new C1(I,I1(f),l)}O&&O.Ru();if(f=O)g.H(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=aHa(a),g.H(a,a.i));if("card"===e.type){c=
a.i;var fa=e&&e.data&&e.data.card_type;f=e.data;if(fa)switch(l=f.tracking||{},l={cH:l.impression,click:l.click,close:l.close,eK:l.teaser_impression,sy:l.teaser_click},I=f.tracking_params||{},O=null,fa){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,le:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Al:I.card?g.ru(I.card):null,Wi:I.teaser?g.ru(I.teaser):null,
Ge:I.icon?g.ru(I.icon):null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,pJ:f.image_url,title:f.title,metaInfo:f.meta_info,url:j1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};x1(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,le:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Al:I.card?
g.ru(I.card):null,Wi:I.teaser?g.ru(I.teaser):null,Ge:I.icon?g.ru(I.icon):null,hv:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:j1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};x1(c,e);break;case "productListing":f.signin_url&&(O=j1({target:"current",value:f.signin_url}));fa=[];for(var ra=f.offers||[],oa=0;oa<ra.length;oa++)fa.push(new tGa(g.pd(ra[oa].merchant),g.pd(ra[oa].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,le:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Al:I.card?g.ru(I.card):null,Wi:I.teaser?g.ru(I.teaser):null,Ge:I.icon?g.ru(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Tv:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:j1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),O6:O,N6:f.signin_title?f.signin_title:void 0,M6:f.signin_message?f.signin_message:void 0,offers:fa};x1(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,le:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Al:I.card?g.ru(I.card):null,Wi:I.teaser?g.ru(I.teaser):
null,Ge:I.icon?g.ru(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Tv:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:j1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};x1(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,le:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Al:I.card?g.ru(I.card):null,Wi:I.teaser?g.ru(I.teaser):null,Ge:I.icon?g.ru(I.icon):null,hv:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:j1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},x1(c,e)}}else xGa(a.i,e);c=!0}}c&&(L0(a.player),a.Dx())},dHa=function(a,b){var c=!1;
a.i||(a.i=aHa(a),g.H(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(yGa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.Fw(b.headerText):"",g.Ne(c.tb,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ca=b.trackingParams?g.ru(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.ru(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ge=b.icon.infoCardIconRenderer.trackingParams?
g.ru(b.icon.infoCardIconRenderer.trackingParams):null,L0(a.player),a.Dx())},eHa=function(a,b,c,d,e){if(!a.player.T().Ub){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new kGa("openUrl","click",new iGa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Fw(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Fw(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Fw(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Fw(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.Fw(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Fw(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new oGa(c,"branding","branding",f,d);l=UGa(a);a.l.element.appendChild(l);f=new B1(l,I1(a),f);f.Ru();g.H(f,f);a.J[c]=f}},YGa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.Ha()||(d.unshift(b),b=g.Ra.apply(window,d),a.X.push(g.rp(b)))}},fHa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.BL.prototype.Pr=g.ca(15,function(a,b){var c=g.dM(this.ob());c&&c.Pr(a,b)});
var N0={},O0=null;g.Va(Q0,g.pn);g.k=Q0.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.bb)this.progress=0,this.coords=this.i;else if(this.pc())return!1;P0(this);this.startTime=a=g.Ta();-1==this.bb&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Cx();this.ri("play");-1==this.bb&&this.ri("resume");this.bb=1;var b=g.Qa(this);b in N0||(N0[b]=this);TFa();UFa(this,a);return!0};
g.k.stop=function(a){P0(this);this.bb=0;a&&(this.progress=1);VFa(this,this.progress);this.ri("stop");this.yu()};
g.k.pause=function(){this.pc()&&(P0(this),this.bb=-1,this.ri("pause"))};
g.k.oa=function(){0==this.bb||this.stop(!1);this.ri("destroy");Q0.oe.oa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.xz=function(){this.ri("animate")};
g.k.ri=function(a){this.dispatchEvent(new WFa(a,this))};
g.Va(WFa,g.Bl);g.Va(R0,Q0);R0.prototype.u=g.Ka;R0.prototype.xz=function(){this.u();R0.oe.xz.call(this)};
R0.prototype.yu=function(){this.u();R0.oe.yu.call(this)};
R0.prototype.Cx=function(){this.u();R0.oe.Cx.call(this)};
g.Va(S0,R0);S0.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(T0,g.F);T0.prototype.Na=function(a,b,c,d){c=(0,g.C)(c,d||this.l);a=g.cp(a,b,c);this.i.push(a);return a};
T0.prototype.IB=function(a,b,c,d){c=(0,g.C)(c,d||this.l);a=g.lp(a,b,c);this.i.push(a);return a};
T0.prototype.hc=function(a){g.dp(a);g.lb(this.i,a)};
T0.prototype.oa=function(){g.dp(this.i);this.i.length=0;g.F.prototype.oa.call(this)};g.v(X0,g.SL);g.k=X0.prototype;g.k.load=function(){g.SL.prototype.load.call(this);if(!Y0(this)){var a=g.tia(this.player.getVideoData());a?(a=W0(a,YFa(this)),Z0(this,a,!1)):ZFa(this)}};
g.k.unload=function(){Z0(this,null);this.u&&(this.u.abort(),this.u=null);g.SL.prototype.unload.call(this)};
g.k.tf=function(a,b){return Y0(this)?"loadCustomEndscreenRenderer"===a?(a=W0(b,"new"),Z0(this,a),!0):null:null};
g.k.getOptions=function(){return Y0(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.kb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<gHa.length;f++){var h=Math.abs(b.width-gHa[f]);if(-1===e||d>=h)e=f,d=h}d=hHa[e];this.l&&g.gg(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.vg(e.element,Math.round(h.width*a.width),f);g.og(e.element,m,n);g.nn(e.element,iHa);m=h.left+h.width/2;h=h.top+l/2;g.K(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.nn(e.element,hHa);g.K(e.element,d);(e=g.pe(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.gg(e,"height",f+"px")}}}}};
g.k.je=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())f1(this,this.endscreen.impressionUrls),(a=g.yu())&&this.endscreen.visualElement&&g.Fu(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");f1(this,c.impressionUrls);(b=g.yu())&&g.Fu(b,c.visualElement,void 0);this.player.T().u&&this.player.La("endscreenelementshown",
a)}};
g.k.ag=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.mn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.mn(b,"ytp-ce-shown");this.player.T().u&&this.player.La("endscreenelementhidden",a)}};
g.k.BS=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.nn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var gHa=[346,426,470,506,570,640,853,1280,1920],hHa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),iHa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var jGa={rX:"current",U1:"new"};var lGa={CLOSE:"close",k2:"openUrl",iN:"subscribe"},mGa={kV:"click",CLOSE:"close",KY:"hidden",w3:"rollOut",x3:"rollOver",g4:"shown"};var cHa={GU:"anchored",KK:"branding",CHANNEL:"channel",pX:"cta",OY:"highlightText",LZ:"label",PLAYLIST:"playlist",R2:"popup",p4:"speech",iN:"subscribe",G4:"title",VIDEO:"video",L5:"website"},bHa={KK:"branding",YU:"card",EX:"drawer",MY:"highlight",m0:"marker",Z2:"promotion",TEXT:"text",R5:"widget"};g.v(p1,g.F);g.k=p1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.vw(a,b,{id:c});a.namespace="annotations_module";d&&this.Ma.set(a,d);e&&this.Ra.set(a,e);this.context.G.Ud([a])};
g.k.Ru=function(){this.context.l.subscribe("resize",this.Vv,this)};
g.k.yz=function(a,b,c,d,e,f){if(this.Xa)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Je(this.element)};
g.k.Vv=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=i1(a);if(f){var h=vGa(f,a.target),l=function(){a.i&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.Ip(f||"");m&&n&&(n.v||n.list)?e.context.G.Rj(n.v,b,n.list,!1):g.uI(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);F1(this.context.logger,c,l,d);uGa(f)||(c=g.yu(),d=b.itct,c&&d&&g.Ou(c,g.ru(d)))}};
g.k.oa=function(){this.Ma.clear();this.Ra.clear();g.F.prototype.oa.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.v(u1,p1);g.k=u1.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.wg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Vv=function(){var a=this.isAvailable();g.xg(this.element,a);g.L(this.context.G.getRootNode(),g.TR.IV_DRAWER_ENABLED,a);L0(this.G)};
g.k.destroy=function(){this.G.Pr(!1);try{this.G.getRootNode().removeChild(this.B)}catch(a){}g.Jo(this.X);g.dp(this.ra);this.Ga&&this.Ga.dispose();this.C&&this.C.dispose();p1.prototype.destroy.call(this)};
g.k.IN=function(){if(this.u){F1(this.context.logger,z1(this).tracking.close);var a=g.yu();a&&this.J&&g.Ou(a,this.J);t1(this)}};
g.k.UN=function(){g.L(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.eP=function(){var a=g.yu(),b=z1(this);b=b?b.Ge:this.Ge;a&&b&&g.Mu(a,[b])};
g.k.dP=function(){var a=g.yu(),b=z1(this);b=b?b.Ge:this.Ge;a&&b&&g.Nu(a,[b])};
g.k.hM=function(){var a=z1(this);F1(this.context.logger,a.tracking.eK);var b=g.yu();b&&a&&g.Mu(b,[a.Wi,a.Ge])};
g.k.gP=function(){var a=g.yu(),b=z1(this);a&&b&&g.Nu(a,[b.Wi])};
g.k.gM=function(a){var b=z1(this),c=g.yu();this.i?a?(a=this.context.logger,F1(a,b.tracking.sy),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Wi&&g.Ou(c,b.Wi)):(a=this.context.logger,F1(a,b.tracking.sy),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Ge&&g.Ou(c,b.Ge)):(a=this.context.logger,F1(a,b.tracking.sy),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Ge&&g.Ou(c,this.Ge))};g.v(A1,p1);A1.prototype.Ru=function(){p1.prototype.Ru.call(this);JGa(this)};
A1.prototype.show=function(){p1.prototype.show.call(this);var a=g.yu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Mu(a,[g.ru(b.itct)])};
A1.prototype.hide=function(){p1.prototype.hide.call(this);var a=g.yu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Nu(a,[g.ru(b.itct)])};g.v(B1,A1);
B1.prototype.show=function(){if(!this.isActive){A1.prototype.show.call(this);if(!this.J){g.K(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",Ba:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.xg(this.l,!1);var b=this.createElement({D:"div",Ba:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=qGa(this.annotation))&&q1(this,this.l,b,this.annotation.id,
a.session_data);NGa(this,a);this.J=!0}g.xg(this.element,!0);this.isActive=!0;this.l&&KGa(this,this.l)}};
B1.prototype.hide=function(){this.isActive&&(A1.prototype.hide.call(this),g.xg(this.element,!1),this.isActive=!1)};
B1.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);A1.prototype.destroy.call(this)};g.v(C1,A1);g.k=C1.prototype;g.k.show=function(){this.isActive||(A1.prototype.show.call(this),this.W||(PGa(this),this.W=!0),g.xg(this.element,!0),g.Fm(function(){g.mn(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,E1(this),QGa(this),RGa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.K(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.yz=function(a,b,c,d,e,f){return this.isCollapsed?!1:A1.prototype.yz.call(this,a,b,c,d,e,f)};
g.k.yO=function(a){this.L=!0;D1(this,500,a)};
g.k.xO=function(){this.L=!1;SGa(this)};
g.k.tO=function(a){a.stopPropagation();this.hide()};
g.k.uO=function(a){a.stopPropagation();E1(this);this.isCollapsed=!0;g.K(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();A1.prototype.destroy.call(this)};g.v(G1,g.SL);g.k=G1.prototype;g.k.tf=function(a,b){if(!fHa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.w_(b))&&H1(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(AGa(this.i,b),L0(this.player)),!0}return null};
g.k.getOptions=function(){return fHa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Mp=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.kF||a.L.get(b.videoId)||g.SG(b)||g.TG(b)?!0:!1};
g.k.Dx=function(){if(this.B){var a=this.player.Wa().getVideoContentRect(!0);g.vg(this.B.element,a.width,a.height);g.og(this.B.element,a.left,a.top)}if(this.i){var b=this.player.nj();a=this.i;b=b.width;g.L(a.B,"iv-drawer-small",426>=b);g.L(a.B,"iv-drawer-big",1280<=b)}};
g.k.iM=function(a){VGa(this,a.state);g.V(a.state,2)&&(this.Kh()&&this.wk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Pr(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Up(h)&&h.responseXML?h.responseXML:null)&&(H1(b,h),g.K(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.SL.prototype.load.call(this);VGa(this,this.player.rb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.tp()&&(a=YGa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.I=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().L.get(d);f&&ZGa(e,f);f=f&&(f.Zv||f.Us);if(!c.ul||f)c.ra?WGa(this,c.ra,e):(this.u=function(){b.fb(e)},this.player.addEventListener("videodatachange",this.u));
g.IL(this.player,this.B.element,4);this.Dx();(f=g.SG(c))&&dHa(this,f);(f=g.TG(c))&&f.featuredChannel&&eHa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.fb=function(a){var b=this.player.getVideoData();b.ra&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),WGa(this,b.ra,a))};
g.k.unload=function(){this.player.Cf("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,L0(this.player));this.W=!1;this.I&&(this.I.abort(),this.I=null);this.J={};this.l.hide();g.SL.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.dJ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?$Ga(this):this.load())};
g.k.Kh=function(){return!!this.i&&this.i.isAvailable()};
g.k.wk=function(){this.Kh();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Kh();this.i&&(a?c?s1(this.i,c,b):s1(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):t1(this.i))};
g.k.Pr=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.oa=function(){this.player.T().L.unsubscribe("vast_info_card_add",this.dJ,this);g.mn(this.player.getRootNode(),g.TR.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.up(a[b]);this.X.length=0;g.SL.prototype.oa.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.H(this,a);return a.element};g.YL.annotations_module=G1;g.YL.creatorendscreen=X0;})(_yt_player);
